spring:
  application:
    name: url-shortener

  # ── DataSource ──────────────────────────────────────────
  datasource:
    url: jdbc:postgresql://localhost:5432/url-shortener
    username: postgres
    password: thanh
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 5000

  # ── JPA / Hibernate ────────────────────────────────────
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    open-in-view: false

  # ── Flyway ─────────────────────────────────────────────
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public,iam,link,analytics,platform,billing
    baseline-on-migrate: true

  # ── Redis ──────────────────────────────────────────────
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms

  # ── Cache ──────────────────────────────────────────────
  # Dùng 'simple' (in-memory) khi chưa có Redis, chuyển sang 'redis' khi đã cài Redis
  cache:
    type: redis

# ── Server ─────────────────────────────────────────────
server:
  port: 8080
  servlet:
    context-path: /

# ── App Custom Properties ─────────────────────────────
app:
  jwt:
    secret: url-shortener-jwt-secret-key-change-this-in-production-2026-thanhnd05
    access-token-expiration-ms: 900000        # 15 phút
    refresh-token-expiration-ms: 604800000    # 7 ngày
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5173
  vnpay:
    tmn-code: NZCRQJ6U                  # Thay bằng mã từ VNPay Sandbox
    hash-secret: Q4K67KVGHMSZK5DKM3RHXPEM2U185SHD            # Thay bằng secret từ VNPay Sandbox
    pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    return-url: https://splicing-lid-parrot.ngrok-free.dev/api/v1/billing/vnpay-return

# ── Logging ────────────────────────────────────────────
logging:
  level:
    com.ThanhND05.url_shortener: DEBUG
    org.springframework.security: DEBUG
    org.flywaydb: INFO
