package com.ThanhND05.url_shortener.billing.service;

import com.ThanhND05.url_shortener.common.config.AppProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class VnPayServiceTest {

    @Mock
    private AppProperties appProperties;

    @InjectMocks
    private VnPayService vnPayService;

    private AppProperties.VnPay vnPayConfig;

    @BeforeEach
    void setUp() {
        vnPayConfig = new AppProperties.VnPay();
        vnPayConfig.setTmnCode("TEST_TMN");
        vnPayConfig.setHashSecret("TEST_SECRET_12345678901234567890");
        vnPayConfig.setPayUrl("https://sandbox.vnpayment.vn/paymentv2/vpcpay.html");
        vnPayConfig.setReturnUrl("http://localhost:8080/api/v1/billing/vnpay-return");
    }

    @Test
    void testCreatePaymentUrl_ReturnsValidUrl() {
        // Arrange
        when(appProperties.getVnpay()).thenReturn(vnPayConfig);
        String txnRef = "URLSHORT_20230101120000_ABCD";
        long amount = 50000;
        String orderInfo = "Thanh toan goi PRO";
        String ipAddress = "127.0.0.1";

        // Act
        String paymentUrl = vnPayService.createPaymentUrl(txnRef, amount, orderInfo, ipAddress);

        // Assert
        assertNotNull(paymentUrl);
        assertTrue(paymentUrl.startsWith(vnPayConfig.getPayUrl()));
        assertTrue(paymentUrl.contains("vnp_Amount=" + (amount * 100)));
        assertTrue(paymentUrl.contains("vnp_TxnRef=" + txnRef));
        assertTrue(paymentUrl.contains("vnp_SecureHash="));
    }

    @Test
    void testVerifyChecksum_ValidChecksum_ReturnsTrue() throws Exception {
        // We will test if the verifyChecksum works correctly.
        // Arrange
        when(appProperties.getVnpay()).thenReturn(vnPayConfig);
        
        // Let's create a payment URL and extract its params to simulate VNPay callback
        String paymentUrl = vnPayService.createPaymentUrl("REF123", 10000, "Test", "127.0.0.1");
        
        // Extract query parameters from URL
        String queryString = paymentUrl.substring(paymentUrl.indexOf('?') + 1);
        String[] pairs = queryString.split("&");
        Map<String, String> params = new HashMap<>();
        for (String pair : pairs) {
            int idx = pair.indexOf("=");
            params.put(pair.substring(0, idx), URLDecoder.decode(pair.substring(idx + 1), StandardCharsets.US_ASCII.name()));
        }

        // Act
        boolean isValid = vnPayService.verifyChecksum(params);

        // Assert
        assertTrue(isValid, "The checksum generated by createPaymentUrl should be verified successfully");
    }
    
    @Test
    void testVerifyChecksum_InvalidChecksum_ReturnsFalse() {
        // Arrange
        when(appProperties.getVnpay()).thenReturn(vnPayConfig);
        Map<String, String> params = new HashMap<>();
        params.put("vnp_Amount", "1000000");
        params.put("vnp_TxnRef", "REF123");
        params.put("vnp_SecureHash", "fake_invalid_hash");

        // Act
        boolean isValid = vnPayService.verifyChecksum(params);

        // Assert
        assertFalse(isValid);
    }
    
    @Test
    void testVerifyChecksum_MissingHash_ReturnsFalse() {
        // Arrange
        Map<String, String> params = new HashMap<>();
        params.put("vnp_Amount", "1000000");

        // Act
        boolean isValid = vnPayService.verifyChecksum(params);

        // Assert
        assertFalse(isValid);
    }
}
